# Datasets and Dataloaders

In [15]:
from run_easg import EASGData
from dataset import myEASGDataset
from pathlib import Path
from torch_geometric.loader import DataLoader

ann_path = 'annts_in_new_format/'
with open(ann_path + 'verbs.txt') as f:
    verbs = [l.strip() for l in f.readlines()]

with open(ann_path + 'objects.txt') as f:
    objs = [l.strip() for l in f.readlines()]

with open(ann_path + 'relationships.txt') as f:
    rels = [l.strip() for l in f.readlines()]

path_annts = Path("annts_in_new_format")
path_data = Path('data')

train_original = EASGData(path_annts, path_data, 'train', verbs, objs, rels)
validation_original = EASGData(path_annts, path_data, 'val', verbs, objs, rels)

train_dataset = myEASGDataset(train_original)
validation_dataset = myEASGDataset(validation_original)

batch_size = 1
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(validation_dataset, batch_size=batch_size, shuffle=False)

# Experiments

In [22]:
!python train.py --num_epochs=100

torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size

In [13]:
import torch
edge_index = torch.zeros((2,2), dtype=int)
print(edge_index)
edge_index[1][0] =1
edge_index[1][1] =2
print(edge_index)
nodes_features = torch.randn((3,12))
print(nodes_features)

tensor([[0, 0],
        [0, 0]])
tensor([[0, 0],
        [1, 2]])
tensor([[ 1.1726,  0.9516, -1.0743,  1.6654,  0.0974, -0.5504, -0.9266, -1.7960,
         -0.3173,  0.9697,  0.1209,  0.1658],
        [-1.4384,  0.9174,  0.6253,  0.6105, -0.2256, -0.5218, -0.2977,  1.6856,
          0.2353,  1.6739,  0.6140, -0.0674],
        [ 0.7945,  0.6639,  0.1407,  0.4590,  1.2590, -1.1013, -0.0673, -0.4406,
          0.5766,  0.9457,  0.6505,  0.0359]])


In [11]:
for i in range(3):
    edge_features = torch.mean(nodes_features[edge_index[:, i]], dim=0).values
    print(edge_features)

0
1


In [18]:
torch.mean(nodes_features[edge_index[:, 1]], dim=0)

tensor([ 0.9836,  0.8077, -0.4668,  1.0622,  0.6782, -0.8259, -0.4969, -1.1183,
         0.1297,  0.9577,  0.3857,  0.1009])